#!/bin/bash
#Menu
clear
echo -e ""
echo -e "=============================-Menu-============================="
echo -e "* menu         : List of Main Commands"
echo -e ""
echo -e "=========================-SSH & OpenVPN-========================"
echo -e "* usernew      : Create SSH & OpenVPN Account"
echo -e "* trial        : Generate SSH & OpenVPN Trial Account"
echo -e "* renew        : Extending SSH & OpenVPN Account Active Life"
echo -e "* deluser      : Delete SSH & OpenVPN Account"
echo -e "* member       : Daftar Member SSH & OpenVPN"
echo -e "* delete       : Delete User Expired SSH & OpenVPN"
echo -e "* autokill     : Set up Autokill SSH"
echo -e "* ceklim       : Displays Users Who Do Multi Login SSH"
echo -e "* restart      : Restart Service Dropbear, Webmin, Squid3,"
echo -e "                 OpenVPN dan SSH"
echo -e ""
echo -e "===========================-Wireguard-========================="
echo -e "* addwg       : Create Wireguard Account"
echo -e "* delwg       : Delete Wireguard Account"
echo -e "* renewwg     : Extend Wireguard Account"
echo -e "* wg show      : Check Wireguard User Interface"
echo -e ""
echo -e "==========================-L2TP/IPSEC-========================="
echo -e "* addl2tp     : Creating L2TP / IPSEC Account"
echo -e "* dell2tp     : Deleting L2TP / IPSEC Account"
echo -e "* renewl2tp   : Extend L2TP / IPSEC Account"
echo -e ""
echo -e "=============================-PPTP-============================"
echo -e "* addpptp     : Create Account PPTP"
echo -e "* delpptp     : Delete PPTP Account"
echo -e "* renewpptp   : Extend PPTP Account"
echo -e ""
echo -e "=============================-SSTP-============================"
echo -e "* addsstp     : Create Account SSTP"
echo -e "* delsstp     : Delete SSTP Account"
echo -e "* renewsstp   : Extend SSTP Account"
echo -e ""
echo -e "=============================-SSR-============================="
echo -e "* addssr      : Create SSR Account"
echo -e "* delssr      : Deleting SSR Account"
echo -e "* renewssr    : Extend SSR Account"
echo -e "* ssr          : Show Other SSR Menu"
echo -e ""
echo -e "========================-Shadowsocks OBFS-====================="
echo -e "* addss       : Creating Shadowsocks Account"
echo -e "* delss       : Delete Shadowsocks Account"
echo -e "* renewss     : Extend Shadowsocks Account"
echo -e ""
echo -e "=============================-V2RAY-==========================="
echo -e "* addws        : Create V2RAY Vmess Websocket Account"
echo -e "* delws        : Deleting V2RAY Vmess Websocket Account"
echo -e "* renewws     : Extend V2RAY Vmess Websocket Account"
echo -e "* cert2ray     : Renew Certificate V2RAY Account"
echo -e ""
echo -e "=============================-VLESS-==========================="
echo -e "* addvless        : Create V2RAY Vless Websocket Account"
echo -e "* delvless        : Deleting V2RAY Vless Websocket Account"
echo -e "* renewvless     : Extend V2RAY Vless Websocket Account"
echo -e ""
echo -e "=============================-Trojan-=========================="
echo -e "* addtr        : Create Trojan Account"
echo -e "* deltr        : Deleting Trojan Account"
echo -e "* renewtr     : Extend Trojan Account"
echo -e ""
echo -e "=============================-SYSTEM-=========================="
echo -e "* ram          : Check Usage of VPS Ram"
echo -e "* reboot       : Reboot VPS"
echo -e "* speedtest    : Speedtest VPS"
echo -e "* info         : Displaying System Information"
echo -e "* about        : Info Script Auto Install"
echo -e ""
echo -e "==============================================================="
echo -e ""

